# Explore here

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
main_df = pd.read_csv("https://breathecode.herokuapp.com/asset/internal-link?id=421&path=diabetes.csv")

In [3]:
main_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
# First separate train and test data and the features from outcome
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(main_df)

In [7]:
X_train = train_df.drop(columns= ["Outcome"])
y_train = train_df["Outcome"]

X_test = test_df.drop(columns= ["Outcome"])
y_test = test_df["Outcome"]

In [8]:
from sklearn.tree import DecisionTreeClassifier

In [9]:
dt_model= DecisionTreeClassifier()

dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [10]:
#import all metrics we could need

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

In [11]:
def model_evaluator(X_matrix, y_target, model):
    """Makes predictions and prints out various evaluation metrics"""
    preds = model.predict(X_matrix)
    print(f"Accuracy score: {accuracy_score(y_true=y_target, y_pred=preds)}")
    print(f"Precision score: {precision_score(y_true=y_target, y_pred=preds)}")
    print(f"Recall score: {recall_score(y_true=y_target, y_pred=preds)}")
    print(f"Confusion matrix: \n{confusion_matrix(y_true=y_target, y_pred=preds)}")
    print(f"Classification report: \n{classification_report(y_true=y_target, y_pred=preds)}")

In [12]:
model_evaluator(X_train, y_train, dt_model)

Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0
Confusion matrix: 
[[375   0]
 [  0 201]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       375
           1       1.00      1.00      1.00       201

    accuracy                           1.00       576
   macro avg       1.00      1.00      1.00       576
weighted avg       1.00      1.00      1.00       576



In [13]:
#100% accuracy means our model is overfitting
#we need to make it dumber

In [14]:
from sklearn.tree import plot_tree

In [15]:
plt.figure(figsize=(100,100))
plot_tree(dt_model);

In [16]:
#could cut off a max depth
#or could do that automatically try differemt versions aka hyperparameters

In [17]:
hyperparam_dict = {'criterion': ["gini", "entropy", "log_loss"],
                   "max_depth": [2, 5, 10, 20],
                   "min_samples_split":[2, 5, 10, 15, 25],
                   "min_samples_leaf":[2, 5, 10, 25]
                     }

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
gridsearch_model = GridSearchCV(estimator=DecisionTreeClassifier(), 
                                param_grid=hyperparam_dict, 
                                scoring='recall',
                                verbose=3)


In [20]:
gridsearch_model.fit(X_train, y_train)

Fitting 5 folds for each of 240 candidates, totalling 1200 fits
[CV 1/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.488 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.575 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.675 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.675 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.550 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=5;, score=0.488 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=5;, score=0.575 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=5;, score=0.675 total time=   0.0s
[CV 4/5] END cri

[CV 5/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=10;, score=0.625 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=15;, score=0.683 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=15;, score=0.525 total time=   0.0s
[CV 3/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=15;, score=0.475 total time=   0.0s
[CV 4/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=15;, score=0.575 total time=   0.0s
[CV 5/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=15;, score=0.625 total time=   0.0s
[CV 1/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=25;, score=0.683 total time=   0.0s
[CV 2/5] END criterion=entropy, max_depth=20, min_samples_leaf=25, min_samples_split=25;, score=0.525 total time=   0.0s
[CV 3/5] END criterion=entropy, 

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [2, 5, 10, 20],
                         'min_samples_leaf': [2, 5, 10, 25],
                         'min_samples_split': [2, 5, 10, 15, 25]},
             scoring='recall', verbose=3)

In [21]:
model_evaluator(X_train, y_train, gridsearch_model)

Accuracy score: 0.8194444444444444
Precision score: 0.7740112994350282
Recall score: 0.681592039800995
Confusion matrix: 
[[335  40]
 [ 64 137]]
Classification report: 
              precision    recall  f1-score   support

           0       0.84      0.89      0.87       375
           1       0.77      0.68      0.72       201

    accuracy                           0.82       576
   macro avg       0.81      0.79      0.80       576
weighted avg       0.82      0.82      0.82       576



In [22]:
model_evaluator(X_test, y_test, gridsearch_model)

Accuracy score: 0.7447916666666666
Precision score: 0.68
Recall score: 0.5074626865671642
Confusion matrix: 
[[109  16]
 [ 33  34]]
Classification report: 
              precision    recall  f1-score   support

           0       0.77      0.87      0.82       125
           1       0.68      0.51      0.58        67

    accuracy                           0.74       192
   macro avg       0.72      0.69      0.70       192
weighted avg       0.74      0.74      0.73       192



In [23]:
gridsearch_model.best_params_

{'criterion': 'entropy',
 'max_depth': 5,
 'min_samples_leaf': 5,
 'min_samples_split': 2}

In [24]:
# Save model
from pickle import dump

dump(gridsearch_model, open("best_accuracy_decision_tree_model.sav", "wb"))