# Explore here

In [29]:
# Your code here
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
main_df = pd.read_csv("https://breathecode.herokuapp.com/asset/internal-link?id=421&path=diabetes.csv")

In [31]:
main_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [32]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [33]:
# First separate train and test data and the features from outcome
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(main_df)

In [34]:
#EDA goes here on train_df

In [35]:
X_train = train_df.drop(columns= ["Outcome"])
y_train = train_df["Outcome"]

X_test = test_df.drop(columns= ["Outcome"])
y_test = test_df["Outcome"]

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
dt_model= DecisionTreeClassifier()

dt_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [38]:
#import all metrics we could need

from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

In [39]:
def model_evaluator(X_matrix, y_target, model):
    """Makes predictions and prints out various evaluation metrics"""
    preds = model.predict(X_matrix)
    print(f"Accuracy score: {accuracy_score(y_true=y_target, y_pred=preds)}")
    print(f"Precision score: {precision_score(y_true=y_target, y_pred=preds)}")
    print(f"Recall score: {recall_score(y_true=y_target, y_pred=preds)}")
    print(f"Confusion matrix: \n{confusion_matrix(y_true=y_target, y_pred=preds)}")
    print(f"Classification report: \n{classification_report(y_true=y_target, y_pred=preds)}")

In [40]:
model_evaluator(X_train, y_train, dt_model)

Accuracy score: 1.0
Precision score: 1.0
Recall score: 1.0
Confusion matrix: 
[[376   0]
 [  0 200]]
Classification report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       376
           1       1.00      1.00      1.00       200

    accuracy                           1.00       576
   macro avg       1.00      1.00      1.00       576
weighted avg       1.00      1.00      1.00       576



In [41]:
#100% accuracy means our model is overfitting
#we need to make it dumber

In [42]:
from sklearn.tree import plot_tree

In [43]:
plt.figure(figsize=(100,100))
plot_tree(dt_model);

In [44]:
#could cut off a max depth
#or could do that automatically try differemt versions aka hyperparameters

In [45]:
hyperparam_dict = {'criterion': ["gini", "entropy", "log_loss"],
                   "max_depth": [2, 5, 10, 20],
                   "min_samples_split":[2, 5, 10, 15, 25],
                   "min_samples_leaf":[2, 5, 10, 25]
                     }

In [46]:
from sklearn.model_selection import GridSearchCV

In [63]:
gridsearch_model = GridSearchCV(estimator=DecisionTreeClassifier(), 
                                param_grid=hyperparam_dict, 
                                scoring='recall',
                                verbose=3)


In [64]:
gridsearch_model.fit(X_train, y_train)

Fitting 5 folds for each of 240 candidates, totalling 1200 fits
[CV 1/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.450 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.600 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.475 total time=   0.0s
[CV 4/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.625 total time=   0.0s
[CV 5/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=2;, score=0.525 total time=   0.0s
[CV 1/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=5;, score=0.450 total time=   0.0s
[CV 2/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=5;, score=0.600 total time=   0.0s
[CV 3/5] END criterion=gini, max_depth=2, min_samples_leaf=2, min_samples_split=5;, score=0.475 total time=   0.0s
[CV 4/5] END cri

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [2, 5, 10, 20],
                         'min_samples_leaf': [2, 5, 10, 25],
                         'min_samples_split': [2, 5, 10, 15, 25]},
             scoring='recall', verbose=3)

In [65]:
model_evaluator(X_train, y_train, gridsearch_model)

Accuracy score: 0.8368055555555556
Precision score: 0.8011363636363636
Recall score: 0.705
Confusion matrix: 
[[341  35]
 [ 59 141]]
Classification report: 
              precision    recall  f1-score   support

           0       0.85      0.91      0.88       376
           1       0.80      0.70      0.75       200

    accuracy                           0.84       576
   macro avg       0.83      0.81      0.81       576
weighted avg       0.83      0.84      0.83       576



In [66]:
model_evaluator(X_test, y_test, gridsearch_model)

Accuracy score: 0.7447916666666666
Precision score: 0.6417910447761194
Recall score: 0.6323529411764706
Confusion matrix: 
[[100  24]
 [ 25  43]]
Classification report: 
              precision    recall  f1-score   support

           0       0.80      0.81      0.80       124
           1       0.64      0.63      0.64        68

    accuracy                           0.74       192
   macro avg       0.72      0.72      0.72       192
weighted avg       0.74      0.74      0.74       192



In [67]:
gridsearch_model.best_params_

{'criterion': 'entropy',
 'max_depth': 5,
 'min_samples_leaf': 5,
 'min_samples_split': 5}

{'criterion': 'entropy',
 'max_depth': 5,
 'min_samples_leaf': 25,
 'min_samples_split': 2} 

 The above are the best parameters when scoring on accuracy.
 The params below are on precision

 {'criterion': 'gini',
 'max_depth': 2,
 'min_samples_leaf': 2,
 'min_samples_split': 2}